server:
  port: 7071
## 数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boot?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: 123

#配置主机设置
  application:
    name: GradleBootApplicationClient

  cloud:
      consul:
        host: localhost
        port: 8500
        discovery:
          healthCheckInterval: 15s
          instance-id: ${spring.application.name}
          service-name: ${spring.application.name}

#配置健康检查信息
management:
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: "*"

