/*
 * This file is generated by jOOQ.
*/
package net.canway.pojo;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import net.canway.pojo.tables.User;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Boot extends SchemaImpl {

    private static final long serialVersionUID = 1635443661;

    /**
     * The reference instance of <code>boot</code>
     */
    public static final Boot BOOT = new Boot();

    /**
     * The table <code>boot.user</code>.
     */
    public final User USER = User.USER;

    /**
     * No further instances allowed
     */
    private Boot() {
        super("boot", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            User.USER);
    }
}
