/*
 * This file is generated by jOOQ.
*/
package net.canway.pojo;


import javax.annotation.Generated;

import net.canway.pojo.tables.User;


/**
 * Convenience access to all tables in boot
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>boot.user</code>.
     */
    public static final User USER = User.USER;
}
