/*
 * This file is generated by jOOQ.
*/
package net.canway.pojo.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements Serializable {

    private static final long serialVersionUID = 430289067;

    private UInteger tId;
    private String   tName;
    private Integer  tAge;
    private String   tDept;

    public User() {}

    public User(User value) {
        this.tId = value.tId;
        this.tName = value.tName;
        this.tAge = value.tAge;
        this.tDept = value.tDept;
    }

    public User(
        UInteger tId,
        String   tName,
        Integer  tAge,
        String   tDept
    ) {
        this.tId = tId;
        this.tName = tName;
        this.tAge = tAge;
        this.tDept = tDept;
    }

    public UInteger getTId() {
        return this.tId;
    }

    public void setTId(UInteger tId) {
        this.tId = tId;
    }

    public String getTName() {
        return this.tName;
    }

    public void setTName(String tName) {
        this.tName = tName;
    }

    public Integer getTAge() {
        return this.tAge;
    }

    public void setTAge(Integer tAge) {
        this.tAge = tAge;
    }

    public String getTDept() {
        return this.tDept;
    }

    public void setTDept(String tDept) {
        this.tDept = tDept;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(tId);
        sb.append(", ").append(tName);
        sb.append(", ").append(tAge);
        sb.append(", ").append(tDept);

        sb.append(")");
        return sb.toString();
    }
}
