server:
  port: 8086
spring:
  application:
    #配置主机名
    name: cloud_consul_feign1
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        healthCheckInterval: 15s
        instance-id: ${spring.application.name}
        service-name: ${spring.application.name}

#配置健康检查信息
management:
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: "*"
